{% set version = "2.4.1" %}

package:
  name: r-soildb
  version: {{ version|replace("-", "_") }}

source:
  fn: soilDB_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/soilDB_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/soilDB/soilDB_{{ version }}.tar.gz
  sha256: 5749aebac01ae2a607fe87ca22f59247108de74fe534afdf325bfe6b1dbe8429

build:
  noarch: generic
  number: 0
  script: R CMD INSTALL --build .
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - r-base
    - r-hmisc
    - r-xml2
    - r-aqp
    - r-plyr
    - r-raster
    - r-reshape2
    - r-sp
    - r-curl
  run:
    - r-base
    - r-hmisc
    - r-xml2
    - r-aqp
    - r-plyr
    - r-raster
    - r-reshape2
    - r-sp
    - r-curl

test:
  commands:
    - $R -e "library('soilDB')"  # [not win]
    - "\"%R%\" -e \"library('soilDB')\""  # [win]

about:
  home: http://ncss-tech.github.io/AQP/
  license: GPL (>= 3)
  license_family: GPL3
  summary: A collection of functions for reading data from USDA-NCSS soil databases.

extra:
  recipe-maintainers:
    - conda-forge/r
    - ocefpaf
    - bgruening
    - jdblischak
    - rvalieris
