travis:
  secure:
    BINSTAR_TOKEN: Nj3TruyE/fQUiRb+s8QDScGB2tfKcQ3SUT1AYJ+9eviyo3jvZZnMPY3DbhRZaAaCoKKqlIMGXl0p6PipVkbDrNZaRI/Z79WUHdPePuZ+haJufCw5hg5f0chZqsL2Hc+2PZD8eIeYIEcJFvvo0KGm0E+EP/eKZBCGrGJg733Fl05yObFouxmMt6I008OOe3bginhPmFiZOReQUMbnTVdf8vaavQN5PrxH0G9vH92gmL6ifvGb5+5q0AVX/k9Ded5qD7pxZShE/zNuWk63vZ3t+a2g/u++uu08NRoHTjUXJMNvb44QvzczKRHGo8WeMb5ztSVKav0jbMQKMJL78+0DwJmZZZhrYl0igwCCpBPqdmvYeNwIvOzJjRPBJrHWJRJM3BvhlYvR6NJ+DOTbDMlcQfJcpOrqSyjpQgoR9d3jMKlVADj7bCunKKDzkNtrQb4hLjjl3wRAn5o0lUo4AptZ/Dpy7XrN68GSDnQpcOjsgKFGMFquN/ZXq7CqZ52ZWIMEWuKYkumiXAUxpOS8UkzP2TTVPoG1dbpMghJ9c/s4V0pFHR7UNYa0SWdLRQJ/EheAV3VCuOaOgF/n9WZR+58u2QMHV7zb/ID/8+jHLhzfZg6WUPfqS8zq2PabUaYrrJVYcVfBl9y2WtnJsGA8rUnN5ruxCqmKS89HPICBGmWzo88=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
